FROM python:3.10 AS builder

ENV PYTHONUNBUFFERED 1
ARG CACHEBUST=1
WORKDIR /app
COPY requirements* ./

RUN apt-get update && apt-get -y install ffmpeg

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r ./requirements-celery.txt

COPY . ./

FROM python:3.10-slim AS deployer

COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /app /app

RUN apt-get update && apt-get -y install ffmpeg
RUN pip install --no-cache-dir celery

WORKDIR /app

CMD ["celery", "-A", "tasks", "worker", "--loglevel=info"]