spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${{ secrets.DATABASE_URL }}
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  redis:
    host: "localhost"
    port: 6379
    refreshToken:
      expiration: ${{ secrets.REDIS_REFRESHTOKEN_EXPIRATION }}

  jwt:
    secretKey: ${{ secrets.JWT_SECRETKEY }}

    access:
      expiration: ${{ secrets.JWT_ACCESS_EXPIRATION }}
      header: ${{ secrets.JWT_ACCESS_HEADER }}

    refresh:
      expiration: ${{ secrets.JWT_REFRESH_EXPIRATION }}
      header: ${{ secrets.JWT_REFRESH_HEADER }}

  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${{ secrets.OAUTH_GOOGLE_WEB_CLIENT_ID }}
              client-secret: ${{ secrets.OAUTH_GOOGLE_WEB_CLIENT_SECRET }}
              scope: ${{ secrets.OAUTH_GOOGLE_WEB_SCOPE }}
