version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-tier

  memetory-server:
    image: "junrain/memetory-server"
    ports:
      - "80:8080"
    depends_on:
      - redis
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge #localhost : 172.17.0.1