name: ai

on:
  workflow_dispatch:

  push:
    branches:
      - develop
    paths:
      - "AI/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AI/roop

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: echo "${{ secrets.AI_ENV }}" > .env

      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.KEY }}
          host: ${{ secrets.AI_HOST }}
          username: ${{ secrets.USER_NAME }}
          script: ${{ secrets.AI_SCRIPT }}
